# 预备知识

## 获取和运行本书的代码

> 注意：此为原书方式。运行本笔记的代码，依照 [pytorch.ipynb](../../docs/pytorch.ipynb) 操作。

### 获取代码

```bash
cd read-d2l
git clone -b v1.0.0 --depth 1 https://github.com/d2l-ai/d2l-zh.git
```

### 安装Anaconda

Anaconda: https://www.anaconda.com/products/individual#Downloads

配置镜像源（北外）:

- conda: https://mirrors.bfsu.edu.cn/help/anaconda/
- pip: https://mirrors.bfsu.edu.cn/help/pypi/

<!--
pip config unset global.index-url
-->

### 更新环境

若使⽤GPU版的MXNet,可编辑`environment.yml`把`mxnet==1.5.0`替换成`mxnet-cu102==1.7.0`（CUDA 10.2）。

- mxnet: https://pypi.org/project/mxnet/

```bash
cd d2l-zh
conda env update -f environment.yml
```

### 运行代码

激活环境，

```bash
conda activate gluon
```

打开Jupyter记事本，

```bash
jupyter notebook
```

即可查看和运行代码了。

## 数据操作

在MXNet中，NDArray是⼀个类，也是存储和变换数据的主要⼯具。

In [1]:
import torch

### 创建

创建⼀个⾏向量，

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

获取形状，

In [3]:
x.shape

torch.Size([12])

获取总数，

In [4]:
x.numel()

12

形状改为(3, 4)，

In [5]:
X = x.reshape((3, 4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

创建⼀个各元素为0，形状为(2, 3, 4)的张量，

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

类似地，创建各元素为1的张量，

In [7]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

通过list指定需要创建的NDArray中每个元素的值，

In [8]:
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

随机⽣成NDArray中每个元素的值，

In [9]:
torch.randn((3, 4))

tensor([[ 1.1311, -0.3656,  0.0393, -0.7432],
        [-0.2873,  0.0500, -0.8852,  1.4087],
        [ 0.3329,  0.4718,  1.8190, -1.1372]])