# 预备知识

## 获取和运行本书的代码

> 注意：此为原书方式。运行本笔记的代码，依照 [env.ipynb](../../env.ipynb) 操作。

### 获取代码

```bash
cd read-d2l
git clone -b v1.0.0 --depth 1 https://github.com/d2l-ai/d2l-zh.git
```

### 安装Anaconda

Anaconda: https://www.anaconda.com/products/individual#Downloads

配置镜像源（北外）:

- conda: https://mirrors.bfsu.edu.cn/help/anaconda/
- pip: https://mirrors.bfsu.edu.cn/help/pypi/

<!--
pip config unset global.index-url
-->

### 更新环境

若使⽤GPU版的MXNet,可编辑`environment.yml`把`mxnet==1.5.0`替换成`mxnet-cu102==1.7.0`（CUDA 10.2）。

- mxnet: https://pypi.org/project/mxnet/

```bash
cd d2l-zh
conda env update -f environment.yml
```

### 运行代码

激活环境，

```bash
conda activate gluon
```

打开Jupyter记事本，

```bash
jupyter notebook
```

即可查看和运行代码了。

## 数据操作

在MXNet中，NDArray是⼀个类，也是存储和变换数据的主要⼯具。

In [1]:
import mxnet as mx
# ctx = mx.cpu()
ctx = mx.gpu(0)

### 创建

创建⼀个⾏向量，

In [2]:
x = mx.nd.arange(12, ctx=ctx)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @gpu(0)>

获取形状，

In [3]:
x.shape

(12,)

获取总数，

In [4]:
x.size

12

形状改为(3, 4)，

In [5]:
X = x.reshape((3, 4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @gpu(0)>

创建⼀个各元素为0，形状为(2, 3, 4)的张量，

In [6]:
mx.nd.zeros((2, 3, 4), ctx=ctx)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @gpu(0)>

类似地，创建各元素为1的张量，

In [7]:
mx.nd.ones((3, 4), ctx=ctx)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @gpu(0)>

通过list指定需要创建的NDArray中每个元素的值，

In [8]:
Y = mx.nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], ctx=ctx)
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @gpu(0)>

随机⽣成NDArray中每个元素的值，

In [9]:
mx.nd.random.normal(0, 1, shape=(3, 4), ctx=ctx)


[[-1.3204551   0.68232244 -0.9858383   0.0199282 ]
 [ 0.7842404   0.50066984 -1.0283493   0.98445714]
 [ 0.23791966  0.5675242   0.416008    1.2724396 ]]
<NDArray 3x4 @gpu(0)>